sudo: false
language: node_js
node_js:
- '5.1'
env:
  global:
  - SAUCE_USERNAME: dojo2-ts-ci
  - SAUCE_ACCESS_KEY: e92610e3-834e-4bec-a3b5-6f7b9d874601
  - BROWSERSTACK_USERNAME: dtktestaccount1
  - BROWSERSTACK_ACCESS_KEY: mG2qbEFJCZY2qLsM7yfx
cache:
  directories:
  - node_modules
install:
- travis_retry npm install --global grunt-cli
- travis_retry npm install
script:
- grunt
- grunt intern:saucelabs --combined
- grunt remapIstanbul:ci
- grunt uploadCoverage
